repository = "termapps/publisher"

exclude = ["aur"]

[homebrew]
repository = "termapps/homebrew-tap"

[aur_bin]
name = "publisher"

[scoop]
repository = "termapps/scoop-bucket"

[nix]
repository = "termapps/nixpkgs"

lockfile = false
path     = "%n.nix"
